server:
  port: ${SERVER_PORT:2110} # Port riêng cho Order

spring:
  application:
    name: order-service

  # 1. DATABASE (Database riêng cho Order)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/smart-bin-v2}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}

  # 2. REDIS (Rất quan trọng - Dùng để lưu Giỏ hàng - Cart)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redisadmin}

  # 3. KAFKA (Đóng vai trò Producer - Báo cáo đơn hàng đã thanh toán)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

  # 4. SECURITY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8180/realms/smart-bin-realm}

# 5. CẤU HÌNH FEIGN CLIENT (Để gọi sang service khác kiểm tra kho và voucher)
app:
  feign:
    product-service:
      url: ${PRODUCT_SERVICE_URL:http://localhost:2112}
      internal-secret: ${PRODUCT_INTERNAL_SECRET:SUPER_SECRET_INTERNAL_KEY}
    reward-service:
      url: ${REWARD_SERVICE_URL:http://localhost:2111}
      internal-secret: ${REWARD_INTERNAL_SECRET:SUPER_SECRET_INTERNAL_KEY}
  kafka:
    topics:
      order-events: "order-events-topic"

vnpay:
  tmn-code: ${VNPAY_TMNCODE:GUET6307}
  hash-secret: ${VNPAY-HASHSECRET:1S6DQ95S0HESOZ4ID3OEWRZN7DRJ9ZCH}
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:https://kvbhust.id.vn/shop/vnpay-return}
  version: ${VNPAY_VERSION:2.1.0}
  command: ${VNPAY_COMMAND:pay}