server:
  port: ${IAM_SERVICE_PORT:8080}

spring:
  application:
    name: iam-service

  cache:
    type: redis
    redis:
      time-to-live: ${IAM_CACHE_TTL:3600000}
      cache-null-values: false

  datasource:
    url: ${IAM_DB_URL:jdbc:mariadb://localhost:3306/smart-bin-v2}
    username: ${IAM_DB_USER:admin}
    password: ${IAM_DB_PASS:admin}
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: ${IAM_DB_POOL_TIMEOUT:20000}
      maximum-pool-size: ${IAM_DB_POOL_MAX:10}
      minimum-idle: ${IAM_DB_POOL_MIN:5}
      max-lifetime: ${IAM_DB_POOL_LIFETIME:1200000}
      idle-timeout: ${IAM_DB_POOL_IDLE_TIMEOUT:300000}
      leak-detection-threshold: ${IAM_DB_POOL_LEAK_THRESHOLD:60000}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${IAM_DB_DDL_AUTO:update}
    show-sql: ${IAM_DB_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${IAM_DB_FORMAT_SQL:true}

  data:
    redis:
      host: ${SHARED_REDIS_HOST:localhost}
      port: ${SHARED_REDIS_PORT:6379}
      password: ${SHARED_REDIS_PASS:redisadmin}

  kafka:
    bootstrap-servers: ${SHARED_KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: ${IAM_KAFKA_GROUP_ID:iam-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/smart-bin-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/smart-bin-realm/protocol/openid-connect/certs}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:smart-bin-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:smart-bin-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:yzWEJ5qP2brO2MZuvMQRgSJhTNFnKe1v}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

app:
  internal:
    secret: ${IAM_INTERNAL_SECRET:SUPER_SECRET_INTERNAL_KEY}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}
  kafka:
    topics:
      send-email: ${TOPIC_SEND_EMAIL:send-email-topic}
      sync-user-tenant: ${TOPIC_SYNC_USER_TENANT:sync-user-tenant-topic}
  admin:
    root-email: ${IAM_ADMIN_ROOT_EMAIL:kieubao2k4@gmail.com}
    root-password: ${IAM_ADMIN_ROOT_PASS:12345678}
  tenant:
    default-email: ${IAM_TENANT_DEFAULT_EMAIL:default_tenant@smartbin.com}
    default-password: ${IAM_TENANT_DEFAULT_PASS:12345678}

google:
  recaptcha:
    secret: ${GOOGLE_CAPTCHA_SECRET:6Lc675ssAAAAAPBj08i1ho7E4BkoX-8RkL6EjmoU}
    verify-url: ${GOOGLE_URL:https://www.google.com/recaptcha/api/siteverify}
    threshold: ${GOOGLE_THRESHOLD:0.5}