"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type LanguageCode = "en" | "vi";

export const LANGUAGE_STORAGE_KEY = "admin_language";

const labels: Record<LanguageCode, string> = {
  en: "English",
  vi: "Tiếng Việt",
};

// 1. Định nghĩa base keys từ tiếng Anh để làm chuẩn (đã xóa 15 keys trùng lặp)
const enTranslations = {
  adminHub: "Admin Hub",
  adminHubDescription: "Manage your fleet, partners, and system settings securely.",
  appName: "InnoEco",
  alreadyHaveAccount: "Already have an account?",
  avatarUpdated: "Avatar updated successfully.",
  cancel: "Cancel",
  changeAvatar: "Change Avatar",
  changePassword: "Change Password",
  chooseLanguage: "Language",
  confirmNewPassword: "Confirm New Password",
  continueWithGoogle: "Continue with Google",
  createAccount: "Create Account",
  createAccountDescription: "Set up your InnoEco account to start managing your devices.",
  currentLanguage: "Current Language",
  currentPassword: "Current Password",
  dashboardLabel: "Dashboard",
  defaultRole: "Admin",
  deviceGroups: "Device Groups",
  devices: "Devices",
  dontHaveAccount: "Don't have an account?",
  editProfile: "Edit Profile",
  editYourDetails: "Edit your display name and avatar",
  email: "Email",
  emailAddress: "Email Address",
  enterCurrentPassword: "Enter current password",
  enterNewPassword: "Enter new password",
  firstName: "First Name",
  forgotPassword: "Forgot password?",
  fullAccess: "Full Access",
  fullName: "Full Name",
  labelEnglish: "English",
  labelVietnamese: "Vietnamese",
  languageDescription: "Choose the language used across the admin interface.",
  limitedAccess: "Limited Access",
  loadingRole: "Loading role...",
  loginDescription: "Sign in to manage your devices and account.",
  manageProfile: "Manage your profile details, avatar, and security preferences",
  myAccount: "My Account",
  newPassword: "New Password",
  noData: "-",
  overview: "Overview",
  passwordLabel: "Password",
  passwordChanged: "Your password has been changed successfully!",
  partners: "Partners",
  profileInfo: "Profile Info",
  profileInfoDescription: "Keep your workspace identity up to date.",
  profileUpdated: "Profile updated successfully!",
  register: "Register",
  registrationSuccess: "Registration successful! Please check your email to activate your account.",
  saveProfile: "Save Profile",
  saving: "Saving...",
  security: "Security",
  securityDescription: "Update your password to keep your InnoEco dashboard safe.",
  settings: "Settings",
  signIn: "Sign in",
  signedInAs: "Signed in as",
  signOut: "Sign Out",
  signingIn: "Signing in...",
  staySecure: "Stay secure",
  systemAlerts: "System Alerts",
  updateAvatar: "Update Avatar",
  updateAvatarButton: "Save Avatar",
  updateLoginPassword: "Update your login password",
  updatePackages: "Update Packages",
  updateProfile: "Update Profile",
  updateRouting: "Update Routing",
  users: "Users",
  welcomeToInnoEco: "Welcome to InnoEco",
  zoom: "Zoom",
  creating: "Creating...",
  lastName: "Last Name",
  confirmPassword: "Confirm Password",
  profileOverview: "Avatar and profile overview",
  passwordTooWeak: "Password must be at least 8 characters and include an uppercase letter, a number, and a special character.",
  passwordMismatch: "Password confirmation does not match.",
  registrationFailed: "Registration failed",
  serverError: "Failed to connect to the server",
  passwordStrength: "Password Strength",
  strengthWeak: "Weak",
  strengthFair: "Fair",
  strengthGood: "Good",
  strengthStrong: "Strong",
  resetPasswordTitle: "Reset Your Password",
  resetPasswordDesc: "Enter the email address associated with your InnoEco account, and we'll send you a link to reset your password.",
  resetPasswordSuccessFallback: "If there's an InnoEco account associated with this email, we've sent you instructions to reset your password.",
  resetPasswordError: "We couldn't process your request right now. Please try again later.",
  checkYourInbox: "Check your inbox",
  backToLogin: "Back to Login",
  sending: "Sending...",
  sendResetLink: "Send Reset Link",
  verifyEmailTitle: "Verify Your Email",
  verifyEmailDesc: "Just a moment while we confirm your email address.",
  verifyEmailInvalidLink: "This link doesn't look right. Please check your email again.",
  verifyEmailSuccess: "Your email is now verified! Welcome to InnoEco.",
  verifyEmailExpired: "This verification link has expired or is invalid. Please request a new one below.",
  verifyEmailEmpty: "Please enter an email address so we can resend the link.",
  verifyEmailResent: "We've sent a new verification link to your inbox. Please check your email.",
  verifyEmailResendError: "We couldn't send the email right now. Please try again later.",
  confirmingEmail: "Confirming your email...",
  pleaseWait: "Please wait a moment.",
  emailVerified: "Email Verified!",
  takingYouToLogin: "Taking you to the login page in",
  seconds: "seconds.",
  goToLogin: "Go to Login",
  verificationFailed: "Verification Failed",
  sendNewLinkTo: "Send a new link to:",
  sendNewVerificationLink: "Send New Verification Link",
  loading: "Loading...",
  orContinueWith: "OR CONTINUE WITH",
  loginNoPermission: "This account does not have permission to access the dashboard.",
  signInErrorFallback: "Unable to sign in. Please try again.",
  googleSignInFailed: "Google sign-in failed.",
  setNewPasswordTitle: "Set New Password",
  setNewPasswordDesc: "Choose a strong password to secure your account.",
  invalidResetLink: "The password reset link is invalid. Please request a new one.",
  resetLinkExpired: "This reset link is invalid or has expired. Please request a new password reset link.",
  passwordUpdated: "Password updated",
  passwordResetSuccess: "Your password has been reset successfully.",
  min8Chars: "Minimum 8 characters",
  reEnterPassword: "Re-enter password",
  processing: "Processing...",
  resetPasswordBtn: "Reset Password",
  changePasswordDesc: "Update your password regularly to keep your account secure.",
  newPasswordSameAsCurrent: "The new password must be different from the current password.",
  changePasswordError: "Current password is incorrect or an unexpected error occurred.",
  passwordUpdatedSuccess: "Your account password has been updated successfully.",
  backToAccountHome: "Back to Account Home",
  reEnterNewPassword: "Re-enter new password",
  dashboardLoadErrorUser: "Oops! We couldn't load your dashboard right now.",
  dashboardLoadErrorAdmin: "Oops! We couldn't load your dashboard statistics right now.",
  yourAccount: "Your account",
  myDevices: "My Devices",
  myDevicesSubtitle: "Live device map and location overview",
  onlineStatus: "Online",
  offlineStatus: "Offline",
  activeUsers: "Active Users",
  innoecoDevices: "InnoEco Devices",
  partnerOrganizations: "Partner Organizations",
  unreadAlerts: "Unread Alerts",
  deviceMapTitle: "InnoEco Device Map",
  deviceMapSubtitle: "Real-time locations of your deployed InnoEco devices",
  operationalGuidelines: "Operational Guidelines",
  operationalGuidelinesSubtitle: "A quick overview of how platform data is managed within your admin hub",
  noteStoreTitle: "InnoEco Store",
  noteStoreBody: "Manage product listings, categories, and the overall lifecycle of items visible to your customers.",
  noteOrdersTitle: "Orders & Fulfillment",
  noteOrdersBody: "Keep track of customer orders from the moment they check out to successful delivery.",
  noteFleetTitle: "InnoEco Fleet Status",
  noteFleetBody: "Easily monitor the health, location, and telemetry of all connected InnoEco devices.",
  noteAlertsTitle: "System Alerts",
  noteAlertsBody: "Stay on top of important updates, user activities, and centralized alerts in real-time.",
  tenantsLoadError: "Oops! We couldn't load the partner list right now.",
  tenantCreatedSuccess: "New InnoEco partner account created successfully!",
  tenantCreateError: "We couldn't create the partner account at this time.",
  tenantStatusUpdateSuccess: "Partner account status successfully updated to {status}!",
  tenantStatusUpdateError: "We couldn't update the partner status right now.",
  innoecoPartners: "InnoEco Partners",
  partnersSubtitle: "Manage partner organizations and their access to the InnoEco platform",
  addPartnerAccount: "Add Partner Account",
  partnersDescription: "Use the popup form to easily set up new partner accounts and manage their details.",
  partnerDirectory: "Partner Directory",
  partnerDirectorySubtitle: "View and quickly update the status of your partner organizations",
  organizationName: "Organization Name",
  accountState: "Account State",
  action: "Action",
  createPartnerAccount: "Create Partner Account",
  createPartnerSubtitle: "Add a new partner organization to your InnoEco network",
  egOrganization: "e.g. GreenTech Corp",
  partnerEmailPlaceholder: "partner@innoeco.com",
  contactEmail: "Contact Email",
  settingsTitle: "InnoEco Settings",
  accountLabel: "Account",
  unnamedUser: "Unnamed User",
  yourFullName: "Your full name",
  adminEmail: "admin@innoeco.com",
  updating: "Updating...",
  openSecurityPanel: "Open the security panel to change your password.",
  launchEditor: "Launch the editor to change your name and details.",
  errorLoadProfile: "We couldn't load your profile details right now.",
  errorReadImage: "Unable to read selected image.",
  errorLoadAvatar: "We couldn't load the selected avatar.",
  errorCropImage: "Unable to crop the selected image.",
  errorResolveAvatarUrl: "We couldn't resolve the uploaded avatar URL.",
  errorUpdateAvatar: "We couldn't update your avatar right now.",
  errorUpdateProfile: "Oops! We couldn't update your profile.",
  errorPasswordsNotMatch: "Oops! Your new passwords don't match.",
  errorChangePassword: "We couldn't change your password right now.",
  systemAlertsTitle: "InnoEco System Alerts",
  systemAlertsSubtitle: "Stay updated and easily manage all your important system notifications in one place.",
  markAllAsRead: "Mark all as read",
  marking: "Marking...",
  markAsRead: "Mark as read",
  readStatus: "Read",
  alertMarkedRead: "InnoEco alert marked as read!",
  allAlertsMarkedRead: "All InnoEco alerts have been marked as read!",
  landingTitle: "InnoEco Dashboard",
  landingSubtitle: "Effortlessly manage your partner accounts, active devices, and system alerts all from one centralized hub.",
  openDashboard: "Open Dashboard",
  ruleMinLength: "At least 8 characters",
  ruleUppercase: "Includes an uppercase letter",
  ruleNumber: "Includes a number",
  ruleSpecialChar: "Includes a special character",
  workspace: "Workspace",
  mapErrorDefault: "Cannot load Mapbox map right now.",
  deviceOnline: "Device Online",
  deviceOffline: "Device Offline",
  statusLabel: "Status:",
  missingMapToken: "Missing NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN in environment.",
  mapFailedToLoad: "Mapbox failed to load:",
  stillLoadingMap: "Still loading map tiles...",
  loadingMap: "Loading map...",
  deviceWithCoordinates: "device with coordinates",
  devicesWithCoordinates: "devices with coordinates",
  onlineLabel: "online",
  offlineLabel: "offline",
  devicePositionsOnly: "Device positions only",
  addressLookupFailed: "Address lookup failed",
  noMatchingAddress: "No matching address found. Please try another keyword.",
  cannotSearchAddress: "Cannot search this address right now.",
  geolocationNotSupported: "Geolocation is not supported by this browser.",
  usingCurrentLocation: "Using your current location.",
  cannotAccessLocation: "Cannot access your current location. Please allow location permission.",
  missingMapboxToken: "Missing NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN.",
  searchAddressPlaceholder: "Search address (house number, street...)",
  findAddressBtn: "Find",
  useCurrentLocationTooltip: "Use current location",
  searchAddressTooltip: "Search address",
  importEmptyFile: "Oops! This file looks empty.",
  importInvalidData: "We couldn't find any valid data. Please ensure your file has at least MAC and Claim Code columns.",
  importNoDevices: "No devices to import",
  importFailedPartial: "Import finished, but {count} devices failed to import.",
  importSuccess: "Successfully imported {count} InnoEco devices!",
  importLabel: "Import InnoEco Devices (CSV / XLSX)",
  noFileSelected: "No file selected yet",
  importPreviewText: "Preview ({count} devices). Showing the first 200.",
  deviceName: "Name",
  macAddress: "MAC Address",
  claimCode: "Claim Code",
  latitude: "Latitude",
  longitude: "Longitude",
  importing: "Importing...",
  importDevicesBtn: "Import Devices",
  editJsonConfig: "Edit JSON Configuration",
  jsonFormatInvalid: "Oops! The JSON format looks invalid.",
  saveConfig: "Save Configuration",
  loadFirmwareDataError: "We couldn't load the firmware data at the moment.",
  ruleUpdatedSuccess: "InnoEco routing rule updated successfully!",
  ruleCreatedSuccess: "New InnoEco routing rule created successfully!",
  ruleSaveError: "We couldn't save your routing rule right now.",
  confirmRemoveRule: "Are you sure you want to remove this update rule?",
  ruleRemovedSuccess: "Routing rule removed successfully!",
  ruleRemoveError: "We couldn't remove this rule right now.",
  firmwareRoutingTitle: "InnoEco Firmware Routing",
  firmwareRoutingSubtitle: "Seamlessly route the correct firmware updates to your deployed InnoEco devices",
  createRoutingRule: "Create Routing Rule",
  firmwareRoutingDesc: "Use the popup editor to easily set up or modify your firmware routing configurations in a clean JSON format.",
  activeRoutingRules: "Active Routing Rules",
  matchingCriteria: "Matching Criteria",
  targetFirmware: "Target Firmware",
  priority: "Priority",
  activeStatus: "Active",
  actions: "Actions",
  yes: "Yes",
  no: "No",
  editBtn: "Edit",
  deleteBtn: "Delete",
  deleting: "Deleting...",
  updateRoutingRule: "Update Routing Rule",
  routingModalSubtitle: "Adjust the matching criteria, target firmware, and priority level",
  deviceMatchingCriteria: "Device Matching Criteria (JSON)",
  selectUpdate: "-- Select an update --",
  priorityLevel: "Priority Level",
  updateRuleBtn: "Update Rule",
  loadUserListError: "Oops! We couldn't load the user list.",
  userStatusUpdateSuccess: "User status successfully updated to {state}!",
  userStatusUpdateError: "We couldn't update the user's status right now.",
  userCreatedSuccess: "New InnoEco user created successfully!",
  userCreateError: "We couldn't create the user at this time.",
  permsUpdateSuccess: "Permissions successfully updated for {name}!",
  permsUpdateError: "We couldn't update the permissions right now.",
  innoecoUsers: "InnoEco Users",
  manageUsersSubtitle: "Manage user accounts, access states, and device permissions",
  addUserBtn: "Add User",
  avatarCol: "Avatar",
  permissionsCol: "Permissions",
  statusCol: "Status",
  manageBtn: "Manage",
  statePending: "Pending",
  stateSuspended: "Suspended",
  stateDeleted: "Deleted",
  permViewDevices: "View Devices",
  permViewDevicesDesc: "Can view device details and telemetry (Default)",
  permEditDevices: "Edit Devices",
  permEditDevicesDesc: "Can update device configurations and settings",
  permDeleteDevices: "Delete Devices",
  permDeleteDevicesDesc: "Can remove devices from the system",
  permControlDevices: "Control Devices",
  permControlDevicesDesc: "Can execute RPC commands (e.g., Open/Close Lid)",
  permViewDefault: "View",
  addNewUserTitle: "Add New User",
  addNewUserDesc: "Provide the user's basic details. The system will handle authentication automatically.",
  userEmailPlaceholder: "user@innoeco.com",
  egJaneDoe: "e.g. Jane Doe",
  closeBtn: "Close",
  createUserBtn: "Create User",
  devicePermsTitle: "Device Permissions",
  updateAccessControlsFor: "Update access controls for",
  savePermsBtn: "Save Permissions",
  loadFirmwaresError: "Oops! We couldn't load your firmware packages.",
  selectFirmwareFile: "Please select a firmware file to upload.",
  invalidFileType: "Invalid file type. Please use one of the following:",
  uploadFirmwareSuccess: "InnoEco update package uploaded successfully!",
  uploadFirmwareError: "We couldn't upload the update package right now.",
  removePackageSuccess: "Update package removed successfully!",
  removePackageError: "We couldn't remove the package.",
  firmwarePackagesTitle: "InnoEco Firmware Packages",
  firmwarePackagesSubtitle: "Manage and distribute your uploaded system updates (.bin and .exe)",
  uploadUpdateBtn: "Upload Update",
  versionCol: "Version",
  targetPlatformCol: "Target Platform",
  fileLinkCol: "File Link",
  descriptionCol: "Description",
  dateAddedCol: "Date Added",
  removeBtn: "Remove",
  pageText: "Page",
  ofText: "of",
  perPage: "per page",
  previousBtn: "Previous",
  nextBtn: "Next",
  uploadModalTitle: "Upload InnoEco Update",
  uploadModalSubtitle: "Add a new firmware package to your system repository",
  versionPlaceholder: "Version Number (e.g., 1.0.3)",
  esp32Option: "ESP32 (InnoEco Edge Node)",
  piOption: "Raspberry Pi (InnoEco Master Hub)",
  releaseNotesPlaceholder: "Release notes or description (optional)",
  allowedFormats: "Allowed formats:",
  selectedFileText: "Selected file:",
  deviceGroupsTitle: "InnoEco Device Groups",
  deviceGroupsSubtitle: "Organize your fleet by assigning devices to dedicated groups",
  codeCol: "Code",
  nameCol: "Name",
  sharedSpecsCol: "Shared Specs",
  alertRulesCol: "Alert Rules",
  groupActionsTitle: "Group Actions",
  groupActionsSubtitle: "Launch the editor to create or update an InnoEco group and its alert behaviors",
  createDeviceGroupBtn: "Create Device Group",
  deviceGroupDesc: "Use the popup editor for all create and update actions to keep your configurations neatly organized.",
  loadDeviceGroupsError: "Failed to load device groups",
  invalidSharedSpecsJson: "The shared specs JSON format isn't quite right. Please double-check it.",
  fillAllAlertFields: "Please fill in all fields for each alert rule, or remove the empty row.",
  invalidThreshold: "Oops! The threshold for the {type} alert is invalid.",
  invalidClearThreshold: "The clearing threshold for the {type} alert seems to be invalid.",
  groupUpdatedSuccess: "InnoEco group updated successfully!",
  groupCreatedSuccess: "New InnoEco group created successfully!",
  saveGroupError: "We couldn't save the device group right now.",
  groupRemovedSuccess: "InnoEco group removed successfully!",
  removeGroupError: "We couldn't remove the device group.",
  updateGroupTitle: "Update InnoEco Group",
  createGroupTitle: "Create InnoEco Group",
  groupModalSubtitle: "Easily adjust the group code, shared specs, and alert rules all in one place.",
  codePlaceholder: "Code (e.g. INNOECO_BIN_60L_V1)",
  friendlyNamePlaceholder: "Friendly Name",
  sharedSpecsJsonLabel: "Shared Specs (JSON)",
  descriptionPlaceholder: "Tell us a bit about this group...",
  alertConfigTitle: "Alert Configuration",
  alertConfigDesc: "Leave this blank if you don't need alerts. Saving without rules will clear existing ones.",
  addRuleBtn: "Add Rule",
  clearAllBtn: "Clear All",
  ruleAlarmNumber: "Rule {num}",
  removeRuleBtn: "Remove",
  alarmTypeLabel: "Alarm Type",
  operatorLabel: "Operator",
  thresholdLabel: "Threshold",
  severityLabel: "Severity",
  clearOperatorLabel: "Clear Operator",
  clearThresholdLabel: "Clear Threshold",
  noAlertRulesMsg: "No alert rules yet! Feel free to add some if this InnoEco group needs monitoring.",
  updateGroupBtn: "Update Group",
  createGroupBtn: "Create Group",
  locationUnavailable: "Location unavailable",
  resolvingAddress: "Resolving address...",
  unknownVersion: "Unknown",
  notSetVersion: "Not Set",
  selectDeviceFirst: "Please select at least one device first.",
  chooseTargetGroup: "Please choose a target group.",
  chooseTargetUser: "Please choose a target user.",
  assignGroupSuccess: "Assigned {count} device(s) to the group!",
  assignUserSuccessPartial: "Assigned {successCount}/{total} devices. {failedCount} device(s) need your attention.",
  assignUserSuccess: "Assigned {count} device(s) to the user!",
  assignmentFailed: "Assignment failed. Please try again.",
  invalidMacFormat: "Invalid MAC address format. Use AA:BB:CC:DD:EE:FF.",
  invalidClaimCode: "Claim code must be exactly 6 characters.",
  deviceNameRequired: "Device name is required.",
  invalidLocationSelected: "Please select a valid location on the map.",
  addDeviceError: "We couldn't add the device right now.",
  deviceConfigFailed: "Device was added, but applying configurations failed.",
  deviceAddedSuccess: "Device added successfully!",
  noTelemetryData: "No telemetry data available.",
  noTelemetryPoints: "No telemetry points in selected range.",
  loadTelemetryError: "Failed to load telemetry data.",
  loadDeviceError: "We couldn't load that device right now.",
  provideValidCoordinates: "Please provide valid coordinates.",
  deviceDetailsUpdated: "Device details updated successfully!",
  updateDeviceDetailsError: "Failed to update device details.",
  loadFirmwareListError: "We couldn't load the firmware list at this time.",
  loadCurrentConfigError: "Couldn't load current configurations.",
  invalidJsonParams: "Please ensure parameters are valid JSON.",
  commandSentSuccess: "Command sent successfully!",
  sendCommandError: "We couldn't send the command right now.",
  noChangesDetected: "No changes detected to update.",
  targetVersionsUpdated: "Target versions updated successfully!",
  saveConfigError: "We couldn't save the new configuration.",
  devicesTitle: "InnoEco Devices",
  devicesSubtitle: "Monitor and manage your active fleet",
  selectCol: "Select",
  locationCol: "Location",
  groupCol: "Group",
  detailsBtn: "Details",
  configureBtn: "Configure",
  assignDevicesTitle: "Assign Devices",
  assignDevicesSubtitle: "Select devices from the table to reassign them",
  selectedDevicesCount: "Selected devices: {count}",
  devicesQueued: "{count} device(s) queued.",
  selectDevicesToStart: "Select one or more devices to start.",
  selectAllBtn: "Select All",
  clearBtn: "Clear",
  assignToGroup: "Assign to Group",
  assignToGroupDesc: "Organize devices into operational areas.",
  targetGroupLabel: "Target Group",
  selectGroupPlaceholder: "Select a group...",
  targetUserLabel: "Target User",
  selectUserPlaceholder: "Select a user...",
  applyAssignmentBtn: "Apply Assignment",
  bulkImportTitle: "Bulk Import",
  quickAddTitle: "Quick Add",
  quickAddSubtitle: "Add a single device manually",
  addDeviceBtn: "Add Device",
  quickAddDesc: "Use this form to onboard a device with location and optional runtime configuration.",
  deviceDetailsTitle: "Device Details & Edit",
  deviceDetailsSubtitle: "View system info and update configurations",
  systemInfoLabel: "System Information",
  claimedAtLabel: "Claimed At",
  createdDateLabel: "Created Date",
  deviceTelemetryLabel: "Device Telemetry",
  loadingTelemetry: "Loading telemetry data...",
  latestFillLevel: "Latest Fill Level",
  latestThrows: "Latest Throws",
  latestBattery: "Latest Battery",
  recentHistoryLabel: "Recent History",
  timeCol: "Time",
  fillLevelCol: "Fill Level",
  throwsCol: "Throws",
  batteryCol: "Battery",
  firmwareStatusLabel: "Firmware Status",
  edgeNodeLabel: "InnoEco Edge Node (Bin)",
  currentLabel: "Current:",
  targetLabel: "Target:",
  masterHubLabel: "InnoEco Master Hub (Desktop)",
  editableConfigLabel: "Editable Configuration",
  pollingIntervalLabel: "Polling Interval",
  fullThresholdLabel: "Full Threshold",
  secondsPlaceholder: "Seconds",
  percentPlaceholder: "Percent",
  locationMapLabel: "Location Map",
  saveChangesBtn: "Save Changes",
  deviceCommandCenterTitle: "Device Command Center",
  deviceCommandCenterSubtitle: "Execute remote actions and view device responses",
  systemActionsLabel: "System Actions",
  systemActionsDesc: "Trigger immediate system events, updates, and maintenance routines.",
  hardwareControlsLabel: "Hardware Controls",
  hardwareControlsDesc: "Operate physical components and update device configurations.",
  actionSummaryLabel: "Action Summary:",
  executeCommandBtn: "Execute Command",
  deviceResponseLabel: "Device Response",
  selectDeviceToControl: "Please select a device to control.",
  firmwareConfigTitle: "Firmware Configurations",
  firmwareConfigSubtitle: "Select target update packages for your InnoEco device",
  currentBinTarget: "Current Bin Target:",
  currentDesktopTarget: "Current Desktop Target:",
  edgeNodeFirmwareLabel: "Edge Node (Bin) Firmware",
  selectTargetFirmware: "Select target firmware",
  noFirmwareAvailable: "No firmware available",
  currentlySavedTarget: "Currently saved target:",
  masterHubFirmwareLabel: "Master Hub (Desktop) Firmware",
  applyConfigBtn: "Apply Configuration",
  clickConfigurePrompt: "Click Configure on a device to edit target versions.",
  addDeviceModalTitle: "Add Device",
  addDeviceModalSubtitle: "Onboard with location and runtime configuration",
  activationClaimCodeLabel: "Activation Claim Code",
  sixCharsPlaceholder: "6 characters",
  invalidCoordinates: "Invalid coordinates. Latitude: -90..90, Longitude: -180..180.",
  secondsOptional: "Seconds (optional)",
  percentOptional: "Percent (optional)",
  pickLocationMap: "Pick Location on Map",
  clickMapInstruction: "Click map or search address to set coordinates.",
  addingBtn: "Adding...",
  rpcOpenLid: "Open Lid",
  rpcOpenLidDesc: "Send a command to open the device lid.",
  rpcCloseLid: "Close Lid",
  rpcCloseLidDesc: "Send a command to close the device lid.",
  rpcLockBin: "Lock Bin",
  rpcLockBinDesc: "Remotely lock the bin.",
  rpcUnlockBin: "Unlock Bin",
  rpcUnlockBinDesc: "Remotely unlock the bin.",
  rpcForceSync: "Force Sync",
  rpcForceSyncDesc: "Force the device to synchronize its status and data.",
  rpcTriggerAlert: "Trigger Alert",
  rpcTriggerAlertDesc: "Manually trigger an alert on the device.",
  rpcRebootDevice: "Reboot Device",
  rpcRebootDeviceDesc: "Remotely reboot the device.",
  rpcCalibrateSensors: "Calibrate Sensors",
  rpcCalibrateSensorsDesc: "Start the sensor calibration process.",
  rpcSetPollingInterval: "Set Polling Interval",
  rpcSetPollingIntervalDesc: "Update how often the device checks in.",
  rpcClearHardwareErrors: "Clear Hardware Errors",
  rpcClearHardwareErrorsDesc: "Clear existing hardware error states.",
  rpcTriggerOtaUpdate: "Trigger OTA Update",
  rpcTriggerOtaUpdateDesc: "Start an over-the-air update process.",
} as const;

export type TranslationKey = keyof typeof enTranslations;

// 2. Ép kiểu chặt chẽ: Đảm bảo 'vi' phải có ĐẦY ĐỦ các key như 'en'
const translations: Record<LanguageCode, Record<TranslationKey, string>> = {
  en: enTranslations,
  vi: {
    adminHub: "Trung tâm quản trị",
    adminHubDescription: "Quản lý đội thiết bị, đối tác và cài đặt hệ thống an toàn.",
    appName: "InnoEco",
    alreadyHaveAccount: "Đã có tài khoản?",
    avatarUpdated: "Đã cập nhật ảnh đại diện.",
    cancel: "Hủy",
    changeAvatar: "Đổi ảnh đại diện",
    changePassword: "Đổi mật khẩu",
    chooseLanguage: "Ngôn ngữ",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    continueWithGoogle: "Tiếp tục với Google",
    createAccount: "Tạo tài khoản",
    createAccountDescription: "Tạo tài khoản InnoEco để bắt đầu quản lý thiết bị.",
    currentLanguage: "Ngôn ngữ hiện tại",
    currentPassword: "Mật khẩu hiện tại",
    dashboardLabel: "Bảng điều khiển",
    defaultRole: "Quản trị viên",
    deviceGroups: "Nhóm thiết bị",
    devices: "Thiết bị",
    dontHaveAccount: "Chưa có tài khoản?",
    editProfile: "Chỉnh sửa hồ sơ",
    editYourDetails: "Chỉnh sửa tên hiển thị và ảnh đại diện",
    email: "Email",
    emailAddress: "Địa chỉ email",
    enterCurrentPassword: "Nhập mật khẩu hiện tại",
    enterNewPassword: "Nhập mật khẩu mới",
    firstName: "Tên",
    forgotPassword: "Quên mật khẩu?",
    fullAccess: "Toàn quyền",
    fullName: "Họ và tên",
    labelEnglish: "Tiếng Anh",
    labelVietnamese: "Tiếng Việt",
    languageDescription: "Chọn ngôn ngữ sử dụng trong giao diện quản trị.",
    limitedAccess: "Quyền giới hạn",
    loadingRole: "Đang tải vai trò...",
    loginDescription: "Đăng nhập để quản lý thiết bị và tài khoản của bạn.",
    manageProfile: "Quản lý thông tin hồ sơ, ảnh đại diện và bảo mật",
    myAccount: "Tài khoản của tôi",
    newPassword: "Mật khẩu mới",
    noData: "-",
    overview: "Tổng quan",
    passwordLabel: "Mật khẩu",
    passwordChanged: "Đã đổi mật khẩu thành công.",
    partners: "Đối tác",
    profileInfo: "Thông tin hồ sơ",
    profileInfoDescription: "Cập nhật nhận diện của bạn trong hệ thống.",
    profileUpdated: "Đã cập nhật hồ sơ thành công.",
    register: "Đăng ký",
    registrationSuccess: "Đăng ký thành công! Vui lòng kiểm tra email để kích hoạt tài khoản.",
    saveProfile: "Lưu hồ sơ",
    saving: "Đang lưu...",
    security: "Bảo mật",
    securityDescription: "Cập nhật mật khẩu để bảo vệ bảng điều khiển InnoEco.",
    settings: "Cài đặt",
    signIn: "Đăng nhập",
    signedInAs: "Đăng nhập với",
    signOut: "Đăng xuất",
    signingIn: "Đang đăng nhập...",
    staySecure: "Giữ an toàn",
    systemAlerts: "Cảnh báo hệ thống",
    updateAvatar: "Cập nhật ảnh đại diện",
    updateAvatarButton: "Lưu ảnh đại diện",
    updateLoginPassword: "Cập nhật mật khẩu đăng nhập",
    updatePackages: "Gói cập nhật",
    updateProfile: "Cập nhật hồ sơ",
    updateRouting: "Điều hướng cập nhật",
    users: "Người dùng",
    welcomeToInnoEco: "Chào mừng đến với InnoEco",
    zoom: "Thu phóng",
    creating: "Đang tạo...",
    lastName: "Họ",
    confirmPassword: "Xác nhận mật khẩu",
    profileOverview: "Ảnh đại diện và thông tin hồ sơ",
    passwordTooWeak: "Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, số và ký tự đặc biệt.",
    passwordMismatch: "Mật khẩu xác nhận không khớp.",
    registrationFailed: "Đăng ký thất bại",
    serverError: "Không thể kết nối đến máy chủ",
    passwordStrength: "Độ mạnh mật khẩu",
    strengthWeak: "Yếu",
    strengthFair: "Trung bình",
    strengthGood: "Tốt",
    strengthStrong: "Mạnh",
    resetPasswordTitle: "Đặt lại mật khẩu",
    resetPasswordDesc: "Nhập địa chỉ email liên kết với tài khoản InnoEco của bạn và chúng tôi sẽ gửi cho bạn liên kết để đặt lại mật khẩu.",
    resetPasswordSuccessFallback: "Nếu có tài khoản InnoEco liên kết với email này, chúng tôi đã gửi hướng dẫn đặt lại mật khẩu cho bạn.",
    resetPasswordError: "Chúng tôi không thể xử lý yêu cầu của bạn lúc này. Vui lòng thử lại sau.",
    checkYourInbox: "Kiểm tra hộp thư đến",
    backToLogin: "Quay lại đăng nhập",
    sending: "Đang gửi...",
    sendResetLink: "Gửi liên kết đặt lại",
    verifyEmailTitle: "Xác minh Email",
    verifyEmailDesc: "Vui lòng chờ trong giây lát trong khi chúng tôi xác nhận địa chỉ email của bạn.",
    verifyEmailInvalidLink: "Liên kết này có vẻ không đúng. Vui lòng kiểm tra lại email của bạn.",
    verifyEmailSuccess: "Email của bạn đã được xác minh! Chào mừng đến với InnoEco.",
    verifyEmailExpired: "Liên kết xác minh này đã hết hạn hoặc không hợp lệ. Vui lòng yêu cầu liên kết mới dưới đây.",
    verifyEmailEmpty: "Vui lòng nhập địa chỉ email để chúng tôi có thể gửi lại liên kết.",
    verifyEmailResent: "Chúng tôi đã gửi một liên kết xác minh mới đến hộp thư của bạn. Vui lòng kiểm tra email.",
    verifyEmailResendError: "Chúng tôi không thể gửi email lúc này. Vui lòng thử lại sau.",
    confirmingEmail: "Đang xác nhận email của bạn...",
    pleaseWait: "Vui lòng chờ trong giây lát.",
    emailVerified: "Đã xác minh Email!",
    takingYouToLogin: "Tự động chuyển đến trang đăng nhập trong",
    seconds: "giây.",
    goToLogin: "Đến trang đăng nhập",
    verificationFailed: "Xác minh thất bại",
    sendNewLinkTo: "Gửi liên kết mới đến:",
    sendNewVerificationLink: "Gửi liên kết xác minh mới",
    loading: "Đang tải...",
    orContinueWith: "HOẶC TIẾP TỤC VỚI",
    loginNoPermission: "Tài khoản này không có quyền truy cập bảng điều khiển.",
    signInErrorFallback: "Không thể đăng nhập. Vui lòng thử lại.",
    googleSignInFailed: "Đăng nhập bằng Google thất bại.",
    setNewPasswordTitle: "Thiết lập mật khẩu mới",
    setNewPasswordDesc: "Chọn một mật khẩu mạnh để bảo vệ tài khoản của bạn.",
    invalidResetLink: "Liên kết đặt lại mật khẩu không hợp lệ. Vui lòng yêu cầu liên kết mới.",
    resetLinkExpired: "Liên kết đặt lại này không hợp lệ hoặc đã hết hạn. Vui lòng yêu cầu liên kết mới.",
    passwordUpdated: "Đã cập nhật mật khẩu",
    passwordResetSuccess: "Mật khẩu của bạn đã được đặt lại thành công.",
    min8Chars: "Tối thiểu 8 ký tự",
    reEnterPassword: "Nhập lại mật khẩu",
    processing: "Đang xử lý...",
    resetPasswordBtn: "Đặt lại mật khẩu",
    changePasswordDesc: "Cập nhật mật khẩu thường xuyên để bảo vệ tài khoản của bạn an toàn.",
    newPasswordSameAsCurrent: "Mật khẩu mới phải khác với mật khẩu hiện tại.",
    changePasswordError: "Mật khẩu hiện tại không đúng hoặc đã xảy ra lỗi không xác định.",
    passwordUpdatedSuccess: "Mật khẩu tài khoản của bạn đã được cập nhật thành công.",
    backToAccountHome: "Về trang chủ tài khoản",
    reEnterNewPassword: "Nhập lại mật khẩu mới",
    dashboardLoadErrorUser: "Rất tiếc! Chúng tôi không thể tải bảng điều khiển của bạn lúc này.",
    dashboardLoadErrorAdmin: "Rất tiếc! Chúng tôi không thể tải thống kê bảng điều khiển lúc này.",
    yourAccount: "Tài khoản của bạn",
    myDevices: "Thiết bị của tôi",
    myDevicesSubtitle: "Bản đồ thiết bị và tổng quan vị trí trực tiếp",
    onlineStatus: "Trực tuyến",
    offlineStatus: "Ngoại tuyến",
    activeUsers: "Người dùng hoạt động",
    innoecoDevices: "Thiết bị InnoEco",
    partnerOrganizations: "Tổ chức đối tác",
    unreadAlerts: "Cảnh báo chưa đọc",
    deviceMapTitle: "Bản đồ thiết bị InnoEco",
    deviceMapSubtitle: "Vị trí theo thời gian thực của các thiết bị InnoEco đã triển khai",
    operationalGuidelines: "Hướng dẫn vận hành",
    operationalGuidelinesSubtitle: "Tổng quan nhanh về cách dữ liệu nền tảng được quản lý trong trung tâm quản trị",
    noteStoreTitle: "Cửa hàng InnoEco",
    noteStoreBody: "Quản lý danh mục sản phẩm và toàn bộ vòng đời của các mặt hàng hiển thị với khách hàng.",
    noteOrdersTitle: "Đơn hàng & Thực thi",
    noteOrdersBody: "Theo dõi đơn hàng của khách hàng từ lúc thanh toán đến khi giao hàng thành công.",
    noteFleetTitle: "Trạng thái đội thiết bị",
    noteFleetBody: "Dễ dàng theo dõi tình trạng, vị trí và dữ liệu viễn trắc của tất cả thiết bị đang kết nối.",
    noteAlertsTitle: "Cảnh báo hệ thống",
    noteAlertsBody: "Nắm bắt các bản cập nhật quan trọng, hoạt động của người dùng và cảnh báo theo thời gian thực.",
    tenantsLoadError: "Rất tiếc! Chúng tôi không thể tải danh sách đối tác lúc này.",
    tenantCreatedSuccess: "Tài khoản đối tác InnoEco mới đã được tạo thành công!",
    tenantCreateError: "Chúng tôi không thể tạo tài khoản đối tác lúc này.",
    tenantStatusUpdateSuccess: "Trạng thái tài khoản đối tác đã được cập nhật thành {status}!",
    tenantStatusUpdateError: "Chúng tôi không thể cập nhật trạng thái đối tác lúc này.",
    innoecoPartners: "Đối tác InnoEco",
    partnersSubtitle: "Quản lý các tổ chức đối tác và quyền truy cập của họ vào nền tảng InnoEco",
    addPartnerAccount: "Thêm tài khoản đối tác",
    partnersDescription: "Sử dụng biểu mẫu popup để dễ dàng thiết lập tài khoản đối tác mới và quản lý thông tin của họ.",
    partnerDirectory: "Danh bạ đối tác",
    partnerDirectorySubtitle: "Xem và cập nhật nhanh trạng thái của các tổ chức đối tác",
    organizationName: "Tên tổ chức",
    accountState: "Trạng thái tài khoản",
    action: "Hành động",
    createPartnerAccount: "Tạo tài khoản đối tác",
    createPartnerSubtitle: "Thêm một tổ chức đối tác mới vào mạng lưới InnoEco của bạn",
    egOrganization: "VD: GreenTech Corp",
    partnerEmailPlaceholder: "partner@innoeco.com",
    contactEmail: "Email liên hệ",
    settingsTitle: "Cài đặt InnoEco",
    accountLabel: "Tài khoản",
    unnamedUser: "Người dùng ẩn danh",
    yourFullName: "Họ và tên của bạn",
    adminEmail: "admin@innoeco.com",
    updating: "Đang cập nhật...",
    openSecurityPanel: "Mở bảng bảo mật để thay đổi mật khẩu của bạn.",
    launchEditor: "Mở trình chỉnh sửa để thay đổi tên và thông tin của bạn.",
    errorLoadProfile: "Chúng tôi không thể tải thông tin hồ sơ của bạn lúc này.",
    errorReadImage: "Không thể đọc hình ảnh đã chọn.",
    errorLoadAvatar: "Chúng tôi không thể tải ảnh đại diện đã chọn.",
    errorCropImage: "Không thể cắt hình ảnh đã chọn.",
    errorResolveAvatarUrl: "Chúng tôi không thể xử lý URL ảnh đại diện đã tải lên.",
    errorUpdateAvatar: "Chúng tôi không thể cập nhật ảnh đại diện của bạn lúc này.",
    errorUpdateProfile: "Rất tiếc! Chúng tôi không thể cập nhật hồ sơ của bạn.",
    errorPasswordsNotMatch: "Rất tiếc! Mật khẩu mới của bạn không khớp.",
    errorChangePassword: "Chúng tôi không thể thay đổi mật khẩu của bạn lúc này.",
    systemAlertsTitle: "Cảnh báo hệ thống InnoEco",
    systemAlertsSubtitle: "Luôn cập nhật và dễ dàng quản lý tất cả các thông báo hệ thống quan trọng ở cùng một nơi.",
    markAllAsRead: "Đánh dấu tất cả đã đọc",
    marking: "Đang đánh dấu...",
    markAsRead: "Đánh dấu đã đọc",
    readStatus: "Đã đọc",
    alertMarkedRead: "Đã đánh dấu cảnh báo InnoEco là đã đọc!",
    allAlertsMarkedRead: "Tất cả cảnh báo InnoEco đã được đánh dấu là đã đọc!",
    landingTitle: "Bảng điều khiển InnoEco",
    landingSubtitle: "Dễ dàng quản lý tài khoản đối tác, thiết bị đang hoạt động và cảnh báo hệ thống từ một trung tâm duy nhất.",
    openDashboard: "Mở bảng điều khiển",
    ruleMinLength: "Ít nhất 8 ký tự",
    ruleUppercase: "Chứa chữ cái viết hoa",
    ruleNumber: "Chứa chữ số",
    ruleSpecialChar: "Chứa ký tự đặc biệt",
    workspace: "Không gian làm việc",
    mapErrorDefault: "Không thể tải bản đồ Mapbox lúc này.",
    deviceOnline: "Thiết bị trực tuyến",
    deviceOffline: "Thiết bị ngoại tuyến",
    statusLabel: "Trạng thái:",
    missingMapToken: "Thiếu cấu hình NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN trong môi trường.",
    mapFailedToLoad: "Không thể tải Mapbox:",
    stillLoadingMap: "Đang tiếp tục tải bản đồ...",
    loadingMap: "Đang tải bản đồ...",
    deviceWithCoordinates: "thiết bị có tọa độ",
    devicesWithCoordinates: "thiết bị có tọa độ",
    onlineLabel: "trực tuyến",
    offlineLabel: "ngoại tuyến",
    devicePositionsOnly: "Chỉ vị trí thiết bị",
    addressLookupFailed: "Tìm kiếm địa chỉ thất bại",
    noMatchingAddress: "Không tìm thấy địa chỉ phù hợp. Vui lòng thử từ khóa khác.",
    cannotSearchAddress: "Không thể tìm kiếm địa chỉ này lúc này.",
    geolocationNotSupported: "Trình duyệt này không hỗ trợ định vị địa lý.",
    usingCurrentLocation: "Đang sử dụng vị trí hiện tại của bạn.",
    cannotAccessLocation: "Không thể truy cập vị trí hiện tại. Vui lòng cấp quyền vị trí.",
    missingMapboxToken: "Thiếu cấu hình NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN.",
    searchAddressPlaceholder: "Tìm địa chỉ (số nhà, tên đường...)",
    findAddressBtn: "Tìm",
    useCurrentLocationTooltip: "Sử dụng vị trí hiện tại",
    searchAddressTooltip: "Tìm kiếm địa chỉ",
    importEmptyFile: "Rất tiếc! Tệp này có vẻ như đang trống.",
    importInvalidData: "Chúng tôi không tìm thấy dữ liệu hợp lệ nào. Vui lòng đảm bảo tệp của bạn có ít nhất cột MAC và Mã xác thực (Claim Code).",
    importNoDevices: "Không có thiết bị nào để nhập",
    importFailedPartial: "Quá trình nhập hoàn tất, nhưng {count} thiết bị đã nhập thất bại.",
    importSuccess: "Đã nhập thành công {count} thiết bị InnoEco!",
    importLabel: "Nhập thiết bị InnoEco (CSV / XLSX)",
    noFileSelected: "Chưa chọn tệp nào",
    importPreviewText: "Bản xem trước ({count} thiết bị). Đang hiển thị 200 thiết bị đầu tiên.",
    deviceName: "Tên thiết bị",
    macAddress: "Địa chỉ MAC",
    claimCode: "Mã xác thực",
    latitude: "Vĩ độ",
    longitude: "Kinh độ",
    importing: "Đang nhập...",
    importDevicesBtn: "Nhập thiết bị",
    editJsonConfig: "Chỉnh sửa cấu hình JSON",
    jsonFormatInvalid: "Rất tiếc! Định dạng JSON có vẻ không hợp lệ.",
    saveConfig: "Lưu cấu hình",
    loadFirmwareDataError: "Không thể tải dữ liệu firmware lúc này.",
    ruleUpdatedSuccess: "Cập nhật quy tắc điều hướng InnoEco thành công!",
    ruleCreatedSuccess: "Tạo quy tắc điều hướng InnoEco mới thành công!",
    ruleSaveError: "Không thể lưu quy tắc điều hướng lúc này.",
    confirmRemoveRule: "Bạn có chắc chắn muốn xóa quy tắc cập nhật này không?",
    ruleRemovedSuccess: "Xóa quy tắc điều hướng thành công!",
    ruleRemoveError: "Không thể xóa quy tắc này lúc này.",
    firmwareRoutingTitle: "Điều hướng Firmware InnoEco",
    firmwareRoutingSubtitle: "Điều hướng chính xác các bản cập nhật firmware đến thiết bị InnoEco của bạn",
    createRoutingRule: "Tạo quy tắc điều hướng",
    firmwareRoutingDesc: "Sử dụng trình chỉnh sửa để dễ dàng thiết lập hoặc sửa đổi cấu hình điều hướng firmware dưới dạng JSON.",
    activeRoutingRules: "Các quy tắc đang hoạt động",
    matchingCriteria: "Tiêu chí khớp",
    targetFirmware: "Firmware mục tiêu",
    priority: "Độ ưu tiên",
    activeStatus: "Hoạt động",
    actions: "Hành động",
    yes: "Có",
    no: "Không",
    editBtn: "Sửa",
    deleteBtn: "Xóa",
    deleting: "Đang xóa...",
    updateRoutingRule: "Cập nhật quy tắc điều hướng",
    routingModalSubtitle: "Điều chỉnh tiêu chí, firmware mục tiêu và mức độ ưu tiên",
    deviceMatchingCriteria: "Tiêu chí khớp thiết bị (JSON)",
    selectUpdate: "-- Chọn bản cập nhật --",
    priorityLevel: "Mức độ ưu tiên",
    updateRuleBtn: "Cập nhật quy tắc",
    loadUserListError: "Rất tiếc! Chúng tôi không thể tải danh sách người dùng.",
    userStatusUpdateSuccess: "Trạng thái người dùng đã được cập nhật thành {state}!",
    userStatusUpdateError: "Chúng tôi không thể cập nhật trạng thái người dùng lúc này.",
    userCreatedSuccess: "Người dùng InnoEco mới đã được tạo thành công!",
    userCreateError: "Chúng tôi không thể tạo người dùng lúc này.",
    permsUpdateSuccess: "Đã cập nhật quyền thành công cho {name}!",
    permsUpdateError: "Chúng tôi không thể cập nhật quyền lúc này.",
    innoecoUsers: "Người dùng InnoEco",
    manageUsersSubtitle: "Quản lý tài khoản người dùng, trạng thái truy cập và quyền thiết bị",
    addUserBtn: "Thêm người dùng",
    avatarCol: "Ảnh đại diện",
    permissionsCol: "Quyền hạn",
    statusCol: "Trạng thái",
    manageBtn: "Quản lý",
    statePending: "Chờ duyệt",
    stateSuspended: "Đình chỉ",
    stateDeleted: "Đã xóa",
    permViewDevices: "Xem thiết bị",
    permViewDevicesDesc: "Có thể xem chi tiết thiết bị và dữ liệu viễn trắc (Mặc định)",
    permEditDevices: "Sửa thiết bị",
    permEditDevicesDesc: "Có thể cập nhật cấu hình và cài đặt thiết bị",
    permDeleteDevices: "Xóa thiết bị",
    permDeleteDevicesDesc: "Có thể xóa thiết bị khỏi hệ thống",
    permControlDevices: "Điều khiển thiết bị",
    permControlDevicesDesc: "Có thể thực thi các lệnh gọi RPC (VD: Mở/Đóng nắp)",
    permViewDefault: "Xem",
    addNewUserTitle: "Thêm người dùng mới",
    addNewUserDesc: "Cung cấp thông tin cơ bản của người dùng. Hệ thống sẽ tự động xử lý xác thực.",
    userEmailPlaceholder: "user@innoeco.com",
    egJaneDoe: "VD: Nguyễn Văn A",
    closeBtn: "Đóng",
    createUserBtn: "Tạo người dùng",
    devicePermsTitle: "Quyền thiết bị",
    updateAccessControlsFor: "Cập nhật quyền truy cập cho",
    savePermsBtn: "Lưu quyền",
    loadFirmwaresError: "Rất tiếc! Chúng tôi không thể tải danh sách gói cập nhật.",
    selectFirmwareFile: "Vui lòng chọn tệp firmware để tải lên.",
    invalidFileType: "Loại tệp không hợp lệ. Vui lòng sử dụng một trong các định dạng sau:",
    uploadFirmwareSuccess: "Đã tải lên gói cập nhật InnoEco thành công!",
    uploadFirmwareError: "Không thể tải lên gói cập nhật lúc này.",
    removePackageSuccess: "Xóa gói cập nhật thành công!",
    removePackageError: "Không thể xóa gói cập nhật này.",
    firmwarePackagesTitle: "Gói cập nhật InnoEco",
    firmwarePackagesSubtitle: "Quản lý và phân phối các bản cập nhật hệ thống (.bin và .exe)",
    uploadUpdateBtn: "Tải lên bản cập nhật",
    versionCol: "Phiên bản",
    targetPlatformCol: "Nền tảng đích",
    fileLinkCol: "Liên kết tệp",
    descriptionCol: "Mô tả",
    dateAddedCol: "Ngày thêm",
    removeBtn: "Xóa",
    pageText: "Trang",
    ofText: "trên",
    perPage: "trên mỗi trang",
    previousBtn: "Trước",
    nextBtn: "Tiếp theo",
    uploadModalTitle: "Tải lên bản cập nhật InnoEco",
    uploadModalSubtitle: "Thêm gói firmware mới vào kho lưu trữ hệ thống của bạn",
    versionPlaceholder: "Số phiên bản (VD: 1.0.3)",
    esp32Option: "ESP32 (InnoEco Edge Node)",
    piOption: "Raspberry Pi (InnoEco Master Hub)",
    releaseNotesPlaceholder: "Ghi chú phát hành hoặc mô tả (không bắt buộc)",
    allowedFormats: "Định dạng cho phép:",
    selectedFileText: "Tệp đã chọn:",
    deviceGroupsTitle: "Nhóm thiết bị InnoEco",
    deviceGroupsSubtitle: "Tổ chức đội thiết bị của bạn bằng cách gán thiết bị vào các nhóm chuyên dụng",
    codeCol: "Mã",
    nameCol: "Tên",
    sharedSpecsCol: "Thông số chung",
    alertRulesCol: "Quy tắc cảnh báo",
    groupActionsTitle: "Hành động nhóm",
    groupActionsSubtitle: "Mở trình chỉnh sửa để tạo hoặc cập nhật nhóm InnoEco và hành vi cảnh báo",
    createDeviceGroupBtn: "Tạo nhóm thiết bị",
    deviceGroupDesc: "Sử dụng trình chỉnh sửa popup cho mọi thao tác tạo và cập nhật để giữ cấu hình của bạn gọn gàng.",
    loadDeviceGroupsError: "Không thể tải danh sách nhóm thiết bị",
    invalidSharedSpecsJson: "Định dạng JSON thông số chung không đúng. Vui lòng kiểm tra lại.",
    fillAllAlertFields: "Vui lòng điền tất cả các trường cho mỗi quy tắc cảnh báo, hoặc xóa dòng trống.",
    invalidThreshold: "Rất tiếc! Ngưỡng cho cảnh báo {type} không hợp lệ.",
    invalidClearThreshold: "Ngưỡng xóa cho cảnh báo {type} dường như không hợp lệ.",
    groupUpdatedSuccess: "Cập nhật nhóm InnoEco thành công!",
    groupCreatedSuccess: "Tạo nhóm InnoEco mới thành công!",
    saveGroupError: "Không thể lưu nhóm thiết bị lúc này.",
    groupRemovedSuccess: "Đã xóa nhóm InnoEco thành công!",
    removeGroupError: "Không thể xóa nhóm thiết bị.",
    updateGroupTitle: "Cập nhật nhóm InnoEco",
    createGroupTitle: "Tạo nhóm InnoEco",
    groupModalSubtitle: "Dễ dàng điều chỉnh mã nhóm, thông số chung và quy tắc cảnh báo tại cùng một nơi.",
    codePlaceholder: "Mã (VD: INNOECO_BIN_60L_V1)",
    friendlyNamePlaceholder: "Tên gợi nhớ",
    sharedSpecsJsonLabel: "Thông số chung (JSON)",
    descriptionPlaceholder: "Mô tả một chút về nhóm này...",
    alertConfigTitle: "Cấu hình cảnh báo",
    alertConfigDesc: "Để trống nếu bạn không cần cảnh báo. Lưu mà không có quy tắc sẽ xóa các quy tắc hiện có.",
    addRuleBtn: "Thêm quy tắc",
    clearAllBtn: "Xóa tất cả",
    ruleAlarmNumber: "Quy tắc {num}",
    removeRuleBtn: "Loại bỏ",
    alarmTypeLabel: "Loại cảnh báo",
    operatorLabel: "Toán tử",
    thresholdLabel: "Ngưỡng",
    severityLabel: "Mức độ nghiêm trọng",
    clearOperatorLabel: "Toán tử xóa",
    clearThresholdLabel: "Ngưỡng xóa",
    noAlertRulesMsg: "Chưa có quy tắc cảnh báo nào! Hãy thêm một vài quy tắc nếu nhóm InnoEco này cần được giám sát.",
    updateGroupBtn: "Cập nhật nhóm",
    createGroupBtn: "Tạo nhóm",
    locationUnavailable: "Không có thông tin vị trí",
    resolvingAddress: "Đang phân giải địa chỉ...",
    unknownVersion: "Không rõ",
    notSetVersion: "Chưa thiết lập",
    selectDeviceFirst: "Vui lòng chọn ít nhất một thiết bị trước.",
    chooseTargetGroup: "Vui lòng chọn nhóm mục tiêu.",
    chooseTargetUser: "Vui lòng chọn người dùng mục tiêu.",
    assignGroupSuccess: "Đã gán {count} thiết bị vào nhóm!",
    assignUserSuccessPartial: "Đã gán {successCount}/{total} thiết bị. {failedCount} thiết bị cần bạn kiểm tra lại.",
    assignUserSuccess: "Đã gán {count} thiết bị cho người dùng!",
    assignmentFailed: "Gán thất bại. Vui lòng thử lại.",
    invalidMacFormat: "Định dạng MAC không hợp lệ. Sử dụng AA:BB:CC:DD:EE:FF.",
    invalidClaimCode: "Mã xác thực phải dài chính xác 6 ký tự.",
    deviceNameRequired: "Tên thiết bị là bắt buộc.",
    invalidLocationSelected: "Vui lòng chọn một vị trí hợp lệ trên bản đồ.",
    addDeviceError: "Không thể thêm thiết bị lúc này.",
    deviceConfigFailed: "Thiết bị đã được thêm, nhưng áp dụng cấu hình thất bại.",
    deviceAddedSuccess: "Thêm thiết bị thành công!",
    noTelemetryData: "Không có dữ liệu viễn trắc.",
    noTelemetryPoints: "Không có điểm viễn trắc nào trong phạm vi đã chọn.",
    loadTelemetryError: "Không thể tải dữ liệu viễn trắc.",
    loadDeviceError: "Không thể tải thiết bị này lúc này.",
    provideValidCoordinates: "Vui lòng cung cấp tọa độ hợp lệ.",
    deviceDetailsUpdated: "Cập nhật chi tiết thiết bị thành công!",
    updateDeviceDetailsError: "Cập nhật chi tiết thiết bị thất bại.",
    loadFirmwareListError: "Không thể tải danh sách firmware lúc này.",
    loadCurrentConfigError: "Không thể tải các cấu hình hiện tại.",
    invalidJsonParams: "Vui lòng đảm bảo các tham số là JSON hợp lệ.",
    commandSentSuccess: "Đã gửi lệnh thành công!",
    sendCommandError: "Không thể gửi lệnh lúc này.",
    noChangesDetected: "Không phát hiện thay đổi nào để cập nhật.",
    targetVersionsUpdated: "Đã cập nhật các phiên bản mục tiêu thành công!",
    saveConfigError: "Không thể lưu cấu hình mới.",
    devicesTitle: "Thiết bị InnoEco",
    devicesSubtitle: "Giám sát và quản lý đội thiết bị hoạt động của bạn",
    selectCol: "Chọn",
    locationCol: "Vị trí",
    groupCol: "Nhóm",
    detailsBtn: "Chi tiết",
    configureBtn: "Cấu hình",
    assignDevicesTitle: "Phân bổ thiết bị",
    assignDevicesSubtitle: "Chọn thiết bị từ bảng để gán lại chúng",
    selectedDevicesCount: "Đã chọn: {count} thiết bị",
    devicesQueued: "Đã đưa {count} thiết bị vào hàng đợi.",
    selectDevicesToStart: "Chọn một hoặc nhiều thiết bị để bắt đầu.",
    selectAllBtn: "Chọn tất cả",
    clearBtn: "Bỏ chọn",
    assignToGroup: "Gán vào nhóm",
    assignToGroupDesc: "Tổ chức các thiết bị vào các khu vực vận hành.",
    targetGroupLabel: "Nhóm mục tiêu",
    selectGroupPlaceholder: "Chọn nhóm...",
    targetUserLabel: "Người dùng mục tiêu",
    selectUserPlaceholder: "Chọn người dùng...",
    applyAssignmentBtn: "Áp dụng phân bổ",
    bulkImportTitle: "Nhập hàng loạt",
    quickAddTitle: "Thêm nhanh",
    quickAddSubtitle: "Thêm thủ công một thiết bị",
    addDeviceBtn: "Thêm thiết bị",
    quickAddDesc: "Sử dụng biểu mẫu này để thêm thiết bị cùng với vị trí và cấu hình tùy chọn.",
    deviceDetailsTitle: "Chi tiết & Chỉnh sửa thiết bị",
    deviceDetailsSubtitle: "Xem thông tin hệ thống và cập nhật cấu hình",
    systemInfoLabel: "Thông tin hệ thống",
    claimedAtLabel: "Thời gian đăng ký",
    createdDateLabel: "Ngày tạo",
    deviceTelemetryLabel: "Dữ liệu viễn trắc",
    loadingTelemetry: "Đang tải dữ liệu viễn trắc...",
    latestFillLevel: "Mức đầy mới nhất",
    latestThrows: "Số lượt ném mới nhất",
    latestBattery: "Pin mới nhất",
    recentHistoryLabel: "Lịch sử gần đây",
    timeCol: "Thời gian",
    fillLevelCol: "Mức đầy",
    throwsCol: "Lượt ném",
    batteryCol: "Pin",
    firmwareStatusLabel: "Trạng thái Firmware",
    edgeNodeLabel: "InnoEco Edge Node (Thùng rác)",
    currentLabel: "Hiện tại:",
    targetLabel: "Mục tiêu:",
    masterHubLabel: "InnoEco Master Hub (Desktop)",
    editableConfigLabel: "Cấu hình có thể chỉnh sửa",
    pollingIntervalLabel: "Chu kỳ lấy dữ liệu",
    fullThresholdLabel: "Ngưỡng báo đầy",
    secondsPlaceholder: "Giây",
    percentPlaceholder: "Phần trăm",
    locationMapLabel: "Bản đồ vị trí",
    saveChangesBtn: "Lưu thay đổi",
    deviceCommandCenterTitle: "Trung tâm điều khiển thiết bị",
    deviceCommandCenterSubtitle: "Thực thi các hành động từ xa và xem phản hồi của thiết bị",
    systemActionsLabel: "Hành động hệ thống",
    systemActionsDesc: "Kích hoạt các sự kiện hệ thống, cập nhật và các lịch trình bảo trì.",
    hardwareControlsLabel: "Điều khiển phần cứng",
    hardwareControlsDesc: "Vận hành các thành phần vật lý và cập nhật cấu hình thiết bị.",
    actionSummaryLabel: "Tóm tắt hành động:",
    executeCommandBtn: "Thực thi lệnh",
    deviceResponseLabel: "Phản hồi từ thiết bị",
    selectDeviceToControl: "Vui lòng chọn một thiết bị để điều khiển.",
    firmwareConfigTitle: "Cấu hình Firmware",
    firmwareConfigSubtitle: "Chọn gói cập nhật mục tiêu cho thiết bị InnoEco của bạn",
    currentBinTarget: "Mục tiêu thùng hiện tại:",
    currentDesktopTarget: "Mục tiêu Desktop hiện tại:",
    edgeNodeFirmwareLabel: "Firmware Edge Node (Thùng rác)",
    selectTargetFirmware: "Chọn firmware mục tiêu",
    noFirmwareAvailable: "Không có firmware",
    currentlySavedTarget: "Mục tiêu hiện đang lưu:",
    masterHubFirmwareLabel: "Firmware Master Hub (Desktop)",
    applyConfigBtn: "Áp dụng cấu hình",
    clickConfigurePrompt: "Nhấn nút Cấu hình trên một thiết bị để sửa phiên bản mục tiêu.",
    addDeviceModalTitle: "Thêm thiết bị",
    addDeviceModalSubtitle: "Đăng ký thiết bị với vị trí và cấu hình hoạt động",
    activationClaimCodeLabel: "Mã xác thực",
    sixCharsPlaceholder: "6 ký tự",
    invalidCoordinates: "Tọa độ không hợp lệ. Vĩ độ: -90..90, Kinh độ: -180..180.",
    secondsOptional: "Giây (không bắt buộc)",
    percentOptional: "Phần trăm (không bắt buộc)",
    pickLocationMap: "Chọn vị trí trên bản đồ",
    clickMapInstruction: "Bấm vào bản đồ hoặc tìm địa chỉ để thiết lập tọa độ.",
    addingBtn: "Đang thêm...",
    rpcOpenLid: "Mở nắp",
    rpcOpenLidDesc: "Gửi lệnh mở nắp thiết bị.",
    rpcCloseLid: "Đóng nắp",
    rpcCloseLidDesc: "Gửi lệnh đóng nắp thiết bị.",
    rpcLockBin: "Khóa thùng",
    rpcLockBinDesc: "Khóa thùng rác từ xa.",
    rpcUnlockBin: "Mở khóa thùng",
    rpcUnlockBinDesc: "Mở khóa thùng rác từ xa.",
    rpcForceSync: "Bắt buộc đồng bộ",
    rpcForceSyncDesc: "Bắt buộc thiết bị đồng bộ hóa trạng thái và dữ liệu.",
    rpcTriggerAlert: "Kích hoạt cảnh báo",
    rpcTriggerAlertDesc: "Kích hoạt cảnh báo trên thiết bị theo cách thủ công.",
    rpcRebootDevice: "Khởi động lại thiết bị",
    rpcRebootDeviceDesc: "Khởi động lại thiết bị từ xa.",
    rpcCalibrateSensors: "Hiệu chuẩn cảm biến",
    rpcCalibrateSensorsDesc: "Bắt đầu quá trình hiệu chuẩn cảm biến.",
    rpcSetPollingInterval: "Cập nhật chu kỳ dữ liệu",
    rpcSetPollingIntervalDesc: "Cập nhật tần suất thiết bị gửi dữ liệu.",
    rpcClearHardwareErrors: "Xóa lỗi phần cứng",
    rpcClearHardwareErrorsDesc: "Xóa các trạng thái lỗi phần cứng hiện tại.",
    rpcTriggerOtaUpdate: "Cập nhật OTA",
    rpcTriggerOtaUpdateDesc: "Bắt đầu quá trình cập nhật không dây (Over-The-Air).",
  },
};

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  languageLabels: Record<LanguageCode, string>;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("en");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    
    if (storedLanguage === "en" || storedLanguage === "vi") {
      setLanguage(storedLanguage);
      document.documentElement.lang = storedLanguage;
    } else {
      document.documentElement.lang = "en";
    }
  }, []);

  useEffect(() => {
    if (!isMounted) return;
    
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language, isMounted]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      languageLabels: labels,
      t: (key) => translations[language][key],
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (context) {
    return context;
  }

  return {
    language: "en" as LanguageCode,
    setLanguage: () => undefined,
    languageLabels: labels,
    t: (key: TranslationKey) => translations.en[key],
  };
}