services:
  minio:
    image: minio/minio
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
        - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - smart_bin_network

  redis:
    image: redis:7.2-alpine
    container_name: redis_smart_bin
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD:-secret_redis_password}
      --notify-keyspace-events Ex
    volumes:
      - ./redis_data:/data
    networks:
      - smart_bin_network

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - smart_bin_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost 
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    command: start-dev --features=token-exchange,admin-fine-grained-authz
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - smart_bin_network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - smart_bin_network

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.0"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1883:1883"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-ce-node
      DATABASE_TS_TYPE: sql 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER} 
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD} 
    depends_on:
      - postgres
    networks:
      - smart_bin_network

networks:
  smart_bin_network:
    driver: bridge