services:
  minio:
    image: minio/minio
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        MINIO_SERVER_URL: ${MINIO_SERVER_URL}
        MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    volumes:
        - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - smart_bin_network

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/smart-bin-system --ignore-existing;
      /usr/bin/mc anonymous set download myminio/smart-bin-system;
      exit 0;
      "
    networks:
      - smart_bin_network

  redis:
    image: redis:7.2-alpine
    container_name: redis_smart_bin
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD:-secret_redis_password}
      --notify-keyspace-events Ex
    volumes:
      - ./redis_data:/data
    networks:
      - smart_bin_network

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - smart_bin_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak_auth
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8180:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      #KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      #KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY_HEADERS: xforwarded
      
    command: start-dev --features=token-exchange,admin-fine-grained-authz --import-realm
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import:ro
    depends_on:
      - postgres
    networks:
      - smart_bin_network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - smart_bin_network

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.0"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1883:1883"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-ce-node
      DATABASE_TS_TYPE: sql 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER} 
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD} 
    depends_on:
      postgres:
        condition: service_started
    networks:
      - smart_bin_network

  mqtt-ws-proxy:
    image: python:3.11-alpine
    container_name: mqtt_ws_proxy
    restart: unless-stopped
    ports:
      - "8081:8081"
    command: sh -c "pip install websockify && websockify 0.0.0.0:8081 thingsboard-ce:1883"
    depends_on:
      - thingsboard-ce
    networks:
      - smart_bin_network

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka_smart_bin
    user: root
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./kafka_data:/tmp/kafka-logs
    networks:
      - smart_bin_network
    
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554/tcp"
      - "8554:8554/udp"
      - "8889:8889/tcp"
      - "8189:8189/udp"
    environment:
      MTX_WEBRTCADDITIONALHOSTS: ${VPS_IP_ADDRESS}
    networks:
      - smart_bin_network

  iam-service:
    image: baokieu/iam-service:latest
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - IAM_SERVICE_PORT=8080
    depends_on:
      - mariadb
      - redis
      - kafka
      - keycloak
    networks:
      - smart_bin_network

  device-service:
    image: baokieu/device-service:latest
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - DEVICE_SERVICE_PORT=8080
    depends_on:
      - mariadb
      - redis
      - kafka
    networks:
      - smart_bin_network

  noti-service:
    image: baokieu/noti-service:latest
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - NOTI_SERVICE_PORT=8080
    depends_on:
      - mariadb
      - redis
      - kafka
    networks:
      - smart_bin_network

  media-service:
    image: baokieu/media-service:latest
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - MEDIA_SERVICE_PORT=8080
    depends_on:
      - mariadb
      - redis
      - minio
    networks:
      - smart_bin_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"   # Mở port 80 để tiếp nhận traffic từ proxy/tunnel nếu cần
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - iam-service
      - device-service
    networks:
      - smart_bin_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/d1ebb6d2-bb41-46ee-a24b-c18a2f68d540.json:/etc/cloudflared/d1ebb6d2-bb41-46ee-a24b-c18a2f68d540.json:ro
    depends_on:
      - nginx
    networks:
      - smart_bin_network
  cms:
    image: baokieu/smart-bin-cms:latest
    container_name: nextjs_cms
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.kvbhust.id.vn
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
    depends_on:
      - iam-service
    networks:
      - smart_bin_network
networks:
  smart_bin_network:
    driver: bridge
